# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanan', models.CharField(max_length=200, verbose_name='方案名称')),
                ('zhiling', models.CharField(max_length=400, verbose_name='指令用例')),
                ('status', models.CharField(choices=[('on', '启用'), ('off', '禁用')], max_length=50, verbose_name='状态')),
                ('params', models.CharField(max_length=300, verbose_name='参数顺序')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cuser', models.CharField(max_length=100, verbose_name='创建人')),
            ],
            options={
                'permissions': (('can_read_command', '读取指令权限'), ('can_change_command', '更改指令权限'), ('can_add_command', '添加指令权限'), ('can_delete_command', '删除指令权限')),
                'db_table': 'ui_command',
                'verbose_name_plural': '指令表',
                'verbose_name': '指令表',
            },
        ),
        migrations.CreateModel(
            name='permis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulename', models.CharField(max_length=200, verbose_name='规则名称')),
                ('opername', models.CharField(max_length=200, verbose_name='对应的函数名')),
                ('chengyuan', models.CharField(max_length=1000, verbose_name='允许列表')),
            ],
            options={
                'permissions': (('can_read_permis', '读取acl权限'), ('can_change_permis', '更改acl权限'), ('can_add_permis', '添加acl权限'), ('can_delete_permis', '删除acl权限')),
                'db_table': 'ui_permis',
                'verbose_name_plural': 'acl表',
                'verbose_name': 'acl表',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descname', models.CharField(max_length=200, verbose_name='备注名')),
                ('nickname', models.CharField(max_length=200, verbose_name='昵称')),
            ],
            options={
                'permissions': (('can_read_person', '读取好友权限'), ('can_change_person', '更改好友权限'), ('can_add_person', '添加好友权限'), ('can_delete_person', '删除好友权限')),
                'db_table': 'ui_person',
                'verbose_name_plural': '好友表',
                'verbose_name': '好友表',
            },
        ),
        migrations.CreateModel(
            name='qun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='群名称')),
            ],
            options={
                'permissions': (('can_read_qun', '读取群权限'), ('can_change_qun', '更改群权限'), ('can_add_qun', '添加群权限'), ('can_delete_qun', '删除群权限')),
                'db_table': 'ui_qun',
                'verbose_name_plural': '群表',
                'verbose_name': '群表',
            },
        ),
        migrations.CreateModel(
            name='rulelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulename', models.CharField(max_length=200, verbose_name='规则名称')),
                ('cuser', models.CharField(max_length=100, verbose_name='创建人')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'permissions': (('can_read_rule', '读取规则权限'), ('can_change_rule', '更改规则权限'), ('can_add_rule', '添加规则权限'), ('can_delete_rule', '删除规则权限')),
                'db_table': 'ui_rulelist',
                'verbose_name_plural': '规则表',
                'verbose_name': '规则表',
            },
        ),
        migrations.AddField(
            model_name='commands',
            name='rulename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_command', to='useraction.rulelist', verbose_name='规则名称'),
        ),
    ]
