# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0003_auto_20181025_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='rulename',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='规则名称'),
        ),
    ]
