# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-25 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0006_auto_20181025_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='rulename',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='comms_to_rule', to='useraction.rulelistmodel', verbose_name='规则名称'),
            preserve_default=False,
        ),
    ]
