# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0007_commands_rulename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='rulename',
            field=models.CharField(max_length=200, verbose_name='规则名称'),
        ),
    ]
