# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0009_auto_20181025_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='rulename',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='rus', to='useraction.rulelistmodel', verbose_name='规则名称'),
        ),
    ]
