# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0010_auto_20181026_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.CharField(default=1, max_length=1000, verbose_name='所属群组'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='isfriend',
            field=models.IntegerField(default=1, verbose_name='是否好友'),
            preserve_default=False,
        ),
    ]
