# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-30 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0011_auto_20181029_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='QunPer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunname', models.CharField(max_length=400, verbose_name='群名称')),
                ('rulename', models.CharField(max_length=400, verbose_name='规则名称')),
                ('ctime', models.DateTimeField(verbose_name='创建时间')),
                ('cuser', models.CharField(max_length=100, verbose_name='创建人')),
            ],
        ),
    ]
