# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-31 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0014_auto_20181031_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qunper',
            name='qunrulename',
        ),
        migrations.AddField(
            model_name='qunper',
            name='qunrulename',
            field=models.ManyToManyField(max_length=400, related_name='rusper', to='useraction.rulelistmodel', verbose_name='规则名称'),
        ),
    ]
