# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-31 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0015_auto_20181031_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qunper',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='qunper',
            name='cuser',
        ),
    ]
