# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-31 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0017_sinper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinper',
            old_name='Sinrulename',
            new_name='qunrulename',
        ),
    ]
