# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0018_auto_20181031_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='所属群组'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isfriend',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否好友'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='昵称'),
        ),
        migrations.AlterModelTable(
            name='qunper',
            table='ui_qunper',
        ),
        migrations.AlterModelTable(
            name='sinper',
            table='ui_sinper',
        ),
    ]
